---
include:
- project: tq-em/public/build/toolchain
  file: ci/bundles.yml
  ref: main
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF == null

- project: tq-em/public/build/toolchain
  file: ci/bundles.yml
  ref: $PUBLIC_TOOLCHAIN_CI_REF
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF


Build Demo Bundle (aarch64):
  extends: .build-aarch64-bundle
  variables:
    TQEM_MACHINE: em-aarch64

Gitleaks:
  extends: .gitleaks

Deploy Snapshot:
  extends: .deploy-snapshot
