---
include:
- project: tq-em/public/build/toolchain
  file: ci/bundles.yml
  ref: $TOOLCHAIN_REF
  rules:
    - if: $TOOLCHAIN_REF
- project: tq-em/public/build/toolchain
  file: ci/bundles.yml
  ref: main
  rules:
    - if: $TOOLCHAIN_REF == null

Build Demo Bundle (aarch64):
  extends: .build-aarch64-bundle
  variables:
    TQEM_MACHINE: em-aarch64

Gitleaks:
  extends: .gitleaks

Deploy:
  extends: .simple-deploy
